name: CRNNTL
channels:
  - rdkit
  - conda-forge
  - pytorch

dependencies:
  - python=3.6
  - tensorflow=1.14.0
  - numpy=1.16.4
  - pandas=1.0.3
  - scikit-learn
  - pytorch=1.2.0
  - skorch=0.10.0
  - rdkit



